version: '3.9'

services:
  web.venone.io:
    container_name: venone_web_app
    build: .
    restart: always
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 runserver:app
    volumes:
      - .:/venone
    ports:
      - "5000:5000"
    env_file:
      - ./.flaskenv

  server.nginx.io:
    container_name: venone_nginx_proxy
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web.venone.io
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  venone.certbot.io:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
